# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'Flux Power Saver' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Flux Power Saver
  pod 'Alamofire', '~> 4.0'
end
